language: cpp

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test

packages:
  - libboost1.55-all-dev

compiler:
  - clang

install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install -y make ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install libboost1.55-all-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install python-sphinx ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install boost155; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then sudo pip install sphinx; fi
  - sudo pip install --upgrade pip
  - sudo pip install sphinx_rtd_theme

script:
  - make
