language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y make
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -q && sudo apt-get install -y clang-3.4 && sudo update-alternatives --set cc /usr/bin/clang && sudo update-alternatives --set c++ /usr/bin/clang++
  - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y boost1.55 
script:
  - make NO_TESTING=1
branches:
  only:
    - master
    - dev
os:
  - linux
  - osx
