application: libsneaker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /styles/(.*\.(css))$
  static_files: styles/\1
  upload: styles/.*\.(css)$

- url: /images/(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: 404.html
  upload: 404.html
