application: libsneaker
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /styles/(.*\.(css))$
  static_files: styles/\1
  upload: styles/.*\.(css)$

- url: /images/(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /
  static_files: index.html
  upload: index.html

- url: /overview/styles/(.*\.(css))$
  static_files: overview/styles/\1
  upload: overview/styles/.*\.(css)$

- url: /overview/images/(.*\.(gif|png|jpg))$
  static_files: overview/images/\1
  upload: overview/images/.*\.(gif|png|jpg)$

- url: /overview/
  static_files: overview/index.html
  upload: overview/index.html

- url: /documentation/_static/(.*\.(gif|png|jpg|css|js))$
  static_files: documentation/_static/\1
  upload: documentation/_static/.*\.(gif|png|jpg|css|js)$

- url: /documentation/(.*\.(gif|png|jpg|css|js))$
  static_files: documentation/\1
  upload: documentation/.*\.(gif|png|jpg|css|js)$

- url: /documentation/src/(.*\.(html))$
  static_files: documentation/src/\1
  upload: documentation/src/.*\.(html)$

- url: /documentation/(.*\.(html))$
  static_files: documentation/\1
  upload: documentation/.*\.(html)$

- url: /documentation/
  static_files: documentation/index.html
  upload: documentation/index.html

- url: /.*
  static_files: 404.html
  upload: 404.html